
import { useEffect, useRef, useState } from 'react'; import { supabase } from '../lib/supabaseClient';
export default function Home(){
  const iframeRef = useRef(); const [role,setRole]=useState('viewer'); const [saving,setSaving]=useState(false);
  useEffect(()=>{ supabase.auth.getSession().then(r=>{ if(r.data.session?.user?.id) fetchRole(r.data.session.user.id); }); const sub=supabase.auth.onAuthStateChange((_,s)=>{ if(s?.session?.user?.id) fetchRole(s.session.user.id); else setRole('viewer'); });
    function onMessage(e){ const msg = e.data || {}; if(msg?.source === 'pae-editor'){ if(msg.type === 'ready'){ /* iframe ready */ } if(msg.type === 'content'){ saveToSupabase(msg.page||'home', msg.html||''); } if(msg.type === 'save-request'){ saveToSupabase(msg.page||'home', msg.html||''); } } }
    window.addEventListener('message', onMessage); return ()=>{ window.removeEventListener('message', onMessage); sub.data?.subscription?.unsubscribe(); };
  },[]);
  async function fetchRole(userId){ if(!userId) { setRole('viewer'); return; } const { data } = await supabase.from('user_roles').select('role').eq('user_id', userId).single(); if(data?.role) setRole(data.role); else setRole('viewer'); }
  async function loadFromSupabase(page='home'){ const { data } = await supabase.from('paginas').select('contenido_html').eq('nombre', page).single(); iframeRef.current?.contentWindow?.postMessage({ source:'nextjs', type:'set-content', page, html: data?.contenido_html || '' }, '*'); }
  async function saveToSupabase(page='home', html=''){ try{ setSaving(true); const up = await supabase.from('paginas').upsert({ nombre: page, contenido_html: html }, { returning: 'minimal' }); if(up.error) throw up.error; alert('Guardado en Supabase ✅'); }catch(err){ alert('Error: '+err.message); } finally{ setSaving(false); } }
  function requestContentFromIframe(){ iframeRef.current?.contentWindow?.postMessage({ source:'nextjs', type:'get-content', page:'home' }, '*'); }
  function toggleEdit(val){ iframeRef.current?.contentWindow?.postMessage({ source:'nextjs', type:'toggle-edit', value: !!val }, '*'); }
  return (<div><section style={{marginBottom:12}}><h1>Sistema de Gestión de Residuos Sólidos</h1><p>Editor visual integrado — los cambios se guardan en Supabase para que todos los vean.</p></section><div style={{display:'flex',gap:10,alignItems:'center',marginBottom:12}}>{(role==='admin'||role==='tecnico')?(<><button className='btn btn-primary' onClick={()=>toggleEdit(true)}>Activar edición</button><button className='btn' onClick={()=>toggleEdit(false)}>Desactivar edición</button><button className='btn' onClick={()=>requestContentFromIframe()}>Guardar cambios</button><button className='btn' onClick={()=>loadFromSupabase('home')}>Recargar desde Supabase</button></>):(<div style={{color:'#64748b'}}>Inicia sesión como admin/tecnico para editar</div>)}</div><div style={{border:'1px solid #e6eef0',borderRadius:12,overflow:'hidden'}}><iframe ref={iframeRef} src="/pae_editor.html" style={{width:'100%',height:'85vh',border:0}} /></div></div>); }
