-- Create tables for pages and user roles
create table if not exists paginas (
  id bigint generated by default as identity primary key,
  nombre text unique not null,
  contenido_json jsonb,
  actualizado timestamptz default now(),
  actualizado_por uuid
);

create table if not exists user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  role text not null check (role in ('admin','tecnico','viewer')),
  created_at timestamptz default now()
);
